### ISSUE TITLE
Not valid .nii files?

### ISSUE THREAD

**Issue by kauttoj** [ColeLab/ColeAnticevicNetPartition#1]
Thanks for the parcellations, great work! 

What files exactly are these?
```
CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_netassignments_LR.dlabel.nii 
CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR.dlabel.nii
```
Despite the extension, they do not appears to be valid NIfTi's.

Error message by load_nii.m:
"Error using load_nii_hdr (line 77)
File "CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR.dlabel.nii"
is corrupted."

Error message by MRIcron:
"Warning: the header file is not in NIfTi format [the first 4 bytes do not have the value 348]. Assuming big-endian data."

**Comment by sivcek** [comment]
These are CIFTI files that can be read and used by [Workbench](https://humanconnectome.org/software/get-connectome-workbench). They are valid NIfTI v2 files, with multiple data segments that represent both left and right surface as well as volume data for subcortical structures and cerebellum. You won't be able to read and use them with "regular" nifti file viewers that only expect volume data, like MRIcron and many others.

**Comment by kauttoj** [comment]
Got it. Thanks!
