### ISSUE TITLE
Ordering of network labels

### ISSUE THREAD

**Issue by amsinha9** [ColeLab/ColeAnticevicNetPartition#11]
In the network_labelfile.txt file, it lists the 12 Cole-Anticevic Networks, but to clarify, does the list order correspond to the network number in increasing order that can be matched up using cortex_parcel_network_assignments.mat?

By this, I mean:

Visual1 - network 1
Visual2 - network 2
Somatomotor - network 3
Cingulo-Opercular - network 4
Language - network 5
Default - network 6
Frontoparietal - network 7
Auditory - network 8
Posterior-Multimodal - network 9
Dorsal-attention - network 10
Ventral-Multimodal - network 11
Orbito-Affective -network 12

**Comment by jielisaji** [comment]
Hi, the values in cortex_parcel_network_assignments.mat do indeed correspond to the "network numbers" in network_labelfile.txt. They denote the network membership of the parcel at that index. For example, parcel index 1 in cortex_parcel_network_assignments.mat has value 1, indicating that it is in network 1, or the Visual1 network. Parcel index 2 in cortex_parcel_network_assignments.mat has value 2, indicating that it is in network 2 (Visual2) and so on.
