### ISSUE TITLE
using GSR atlas on functional data without GSR

### ISSUE THREAD

**Issue by jrasero** [ColeLab/ColeAnticevicNetPartition#13]
Hi,

Firs of all, congratulations for such a wonderful atlas. 

One question, is it OK to use the GSR version of your atlas, even if the functional data to which I will apply the atlas was not preprocessed including that step?

Thanks a lot in advance!

**Comment by jielisaji** [comment]
Hi, yes you may use the wGSR version of the parcellation even if your own data has not been preprocessed with GSR. Note also that the wGSR (with GSR) and woGSR (without GSR) versions of the atlas only differ in the subcortical component of the atlas.

**Comment by jrasero** [comment]
Great @jielisaji , thanks a lot for the clarification!
