### ISSUE TITLE
Possible to get the labelled cortical-subcortical MNI coordinates corresponding to the 12 networks?

### ISSUE THREAD

**Issue by Reine0017** [ColeLab/ColeAnticevicNetPartition#15]
Hello @jielisaji! Thank you so much for this data! :)
I am trying to get the [x,y,z] MNI coordinates corresponding to each of the 12 networks (so something like x,y,z, -> network 1) so I can plot it in a python diagram. May I ask if this dataset is available? If not, may I ask which are the nii cortical-subcortical images where the 12 networks are already labelled? 

My friend and I have tried going through the files, the README, the humanconnectome site, and also tried running the LoadParcellatedDataInPython_Example script too but we're not too sure how we can go about getting the coordinates..

Thanks a lot for your time! >.<

**Comment by jielisaji** [comment]
HI @Reine0017, I'm sorry for the delayed response, I was busy preparing for a talk this week! The parcellation is in the CIFTI space. which uses a surface representation for the cortex and a volume representation for the subcortex. For the surface, you can get a mapping between surface vertices and MNI coordinates with this [wb_command](https://www.humanconnectome.org/software/workbench-command/-surface-coordinates-to-metric); for the subcortex, it is already in the MNI space, so you should be able to extract the coordinates directly.

**Comment by jielisaji** [comment]
The separated cortical surface files are [here](https://github.com/ColeLab/ColeAnticevicNetPartition/tree/master/SeparateHemispheres) as well as subcortex volume files for L and R hemispheres.
To separate the entire subcortex as a volume file you can also use:
`wb_command -cifti-separate CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_netassignments_LR.dlabel.nii COLUMN -volume-all <output subcortex filename.nii> `

**Comment by Reine0017** [comment]
Hey @jielisaji! Thank you so much for replying! :) I'll look into it, I hope you have an amazing talk ahead! :)

**Comment by Reine0017** [comment]
Hey @jielisaji! I've tried running what you suggested and managed to get the coordinates for the subcortex (plotted out diagram below in python), but I'm struggling abit with getting the coordinates for the cortex (with the corresponding network for each coordinate)...may I ask what I should do after getting the func.gii or shape.gii files (outputs from wb_command -surface-coordinates-to-metric?
![image](https://user-images.githubusercontent.com/26247692/101877209-9c7f0480-3bc8-11eb-86f3-6ca8e49b47bb.png)

**Comment by jielisaji** [comment]
Hi there, I think you can get the coordinates from something like this:

`wb_command -label-to-volume-mapping  \
CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_netassignments_R.label.gii \
../S1200.R.midthickness_MSMAll.32k_fs_LR.surf.gii \
../S1200_AverageT1w_restore.nii.gz \
CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_netassignments_R.nii.gz \
-nearest-vertex 1`

Note that I would not recommend using this as a volume-based network parcellation (see note [here](https://github.com/ColeLab/ColeAnticevicNetPartition#volume-version-of-the-glasser-surface-parcels)) but it may serve your needs for visualization purposes.

**Comment by Reine0017** [comment]
Hello @jielisaji, thank you so much for this! I now have it working :) Sorry I took so long to get back to you, I was trying to study more into the neuro side of things to try to understand the reasons behind why it's not recommended. I'll close this issue now. Thank you!! :) <3
