### ISSUE TITLE
Missing hemisphere column values for certain subjects in CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR_LabelKey.txt

### ISSUE THREAD

**Issue by brianpkeane** [ColeLab/ColeAnticevicNetPartition#16]
Using the first column as indices, line 521 shows Dorsal-Attention-01_L_Amgydala.  That line and the ones below do not have a column value for hemisphere (though of course the hemisphere can be inferred from the fourth column). 
![Screen Shot 2021-02-01 at 10 25 52 AM](https://user-images.githubusercontent.com/36307456/106485445-9695f900-647e-11eb-9a8d-e0eb6c23c6e6.png)

**Comment by jielisaji** [comment]
Hi Brian, thank you for catching this! I'll update it with the values filled in by the weekend.

**Comment by brianpkeane** [comment]
My pleasure.  Glad I could be helpful!
Brian

**Comment by jielisaji** [comment]
Updated the file! Thanks again Brian.

**Comment by brianpkeane** [comment]
No problem, and thanks for fixing it!
Brian
