### ISSUE TITLE
Labels for separate hemispheres

### ISSUE THREAD

**Issue by dr-xenia** [ColeLab/ColeAnticevicNetPartition#18]
Dear team, 

I really enjoy your parcellation- thank you so much for this! As I would like to use it as ROIs for my tractography, I need to translate them to MNI space which is really hard using connectome workbench (that is suited for cortex data and does not recognize that the .surf.gii-files that you included contain the subcortex - there is an error message saying: "specified file and direction does not contain the requested surface structure 'CEREBELLUM'/BRAIN_STEM etc). 

I tried to use the .nii.gz-files from the SeparateHemispheres folder, however the amount of regions is not exactly the same as in LR (left hemisphere: 213 regions, right: 180 regions), so I do not know how to label the regions. Could you provide me with the labels for these files? Thanks!

**Comment by jielisaji** [comment]
Hi Xenia, thank you for your interest in our parcellation! If you are using the subcortical files in SeparateHemispheres (i.e. subcortex_atlas_GSR_parcels_L.nii and subcortex_atlas_GSR_parcels_R.nii) these are labelled volume files in MNI space. If you type in `wb_command -file-information subcortex_atlas_GSR_parcels_R.nii` in the command line it should print the label names; in Workbench, clicking on the parcel should report the label in the information window. We did not enforce symmetry in the subcortical solution, hence there are a different number of parcels in the L and R hemispheres. Note also that in the separate-hemisphere files we split the subcortical parcels that transverse the midline in the whole-brain solution (e.g. in the brainstem), so they are represented twice (once in the L file and once in the R).
