### ISSUE TITLE
Mapping from Glasser to Cole Anticevic

### ISSUE THREAD

**Issue by amsinha9** [ColeLab/ColeAnticevicNetPartition#19]
In the cortex_parcel_network_assignments.txt file, do the 360 rows correspond to the the exact same order in Glasser parcellation? Or is there a separate file or way to check if the parcel labels match up? I am trying to do a mapping between Glasser parcels and CAB to get the corresponding network labels.

Thanks!

**Comment by jielisaji** [comment]
Hi, the corresponding Glasser labels for the cortical parcels are provided in the LabelKey.txt file [here](https://github.com/ColeLab/ColeAnticevicNetPartition/blob/master/CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR_LabelKey.txt) under the column "GLASSERLABELNAME". 

The order of the 180 parcels in each hemisphere is consistent between our parcellation and the Glasser parcellation, but note that in bilateral files the Glasser parcellation puts right-hemisphere cortical parcels first, whereas the CAB-NP puts left-hemispheres cortical parcels first.
