### ISSUE TITLE
Seeking your advice of template

### ISSUE THREAD

**Issue by Woo-SungKim** [ColeLab/ColeAnticevicNetPartition#20]
Dear ColeLab team

This is Woo Sung Kim, a Ph.D. student at Jeonbuk National University from Korea.
I have read your article "Mapping the human brain's cortical-subcortical functional network organization." 
After reading your paper, I do have questions about the functional network parcellation mask.
I would be grateful if you can find time for me.
  
- I want to discuss applying the cortical part of the network partition template used in the paper to my analysis. 
  The tool that I currently use for functional connectivity analysis is CONN (https://web.conn-toolbox.org/), so I would like to apply the network partition template in CONN toolbox.
  'Data, software, and the network partition are available here: https:// github.com/ColeLab/ColeAnticevicNetPartition and https://doi.org/10. 5281/zenodo.1455791.'
  When I download the code and files through the address above and checked them, I couldn't find the network partition template. 
  I want to discuss whether I should make and use the network partition template using the 'LoadParcellatedDataInMatlab_Example_cortexonly.m' code. 
 
- I understand subcortex template also assigned with 12 cortical networks. Is there any specific detail of the subcortex template, especially the thalamus? Like thalamus is also parcellated to 12 parts or the whole thalamus is included in some of the 12 cortical networks.

-  If you can provide the network partition template of the cortical part and subcortex (especially the thalamus) in the atlas (3D brain image; ~.nii.gz / ~.nii) format, then would you please provide it for me?

 Thanks for your time and expertise in advance.
  
 Best Wishes
  
 Woo

**Comment by jielisaji** [comment]
Hi Woo, I'm so sorry this completely slipped my mind! The partition template is in CIFTI file format, meaning it uses the "*.dlabel.nii" file extension, e.g. CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_netassignments_LR.dlabel.nii. You can visualize these files using a compatible platform such as Connectome Workbench (https://www.humanconnectome.org/software/connectome-workbench). 

CIFTI files use a hybrid surface-volume structure, whereby the cortical sheet is represented as a surface and the subcortical structures (including thalamus) are in volume space. You can find information about the CIFTI format in the paper [here](https://doi.org/10.1016/j.neuroimage.2013.04.127). You can extract the subcortical volume component of the atlas file using Workbench commands like so:

`wb_command -cifti-separate CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_netassignments_LR.dlabel.nii COLUMN -volume-all SubcortexOnly_ColeAnticevic_NetPartition_wSubcorGSR_netassignments_parcellation.nii`
