### ISSUE TITLE
Glasser to Cole Anticevic subcortical parcels

### ISSUE THREAD

**Issue by amsinha9** [ColeLab/ColeAnticevicNetPartition#21]
How can we map the Glasser parcels to the Cole Anticevic atlas for the subcortical parcels? In CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR_LabelKey.txt, I see that "NETWORKSORTEDORDER" corresponds to the Glasser parcels and "NETWORK" is the mapping to the Cole Anticevic networks, but after row #360 which should start with the subcortical parcels, it is unclear how what network each subcortical parcel corresponds to. It seems as though there are multiple network assignments for the L/R subcortical parcels?

For example, there is "Visual1-01_L-Accumbens"..and so forth for all of the subcortical parcels and then switches to "Somatomotor-01_R-Accumbens", etc.

**Comment by jielisaji** [comment]
Hi, the original Glasser parcellation did not extend to the subcortex, hence in `CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR_LabelKey.txt` the subcortical parcels are marked NA under GLASSERLABELNAME.

The network that each subcortical parcel was assigned to can be found in the NETWORK column (e.g. `Visual1-01_L-Accumbens` is in the Visual1 network). 

The name of each subcortical parcel breaks down as follows: `Network-SubcorticalParcelNumber_Hemisphere-Structure`, so `Visual1-01_L-Accumbens` is the first parcel in the subcortex to be assigned to the Visual1 network, and is located in the left accumbens.
I hope that helps to clear things up?

**Comment by amsinha9** [comment]
That makes sense. I'm still unclear on why there are same subcortical parcels have different labels? For example, there is Cingulo-Opercular-01_L-Accumbens. So does L-Accumbens have multiple network assignments? Or is this different from Visual1-01_L-Accumbens?

**Comment by jielisaji** [comment]
Hi yes -- `Accumbens` is the name of one of the subcortical structures (similar to `Cerebellum`, `Thalamus` etc.), not the name of one of the parcels! There are multiple parcels making up the Accumbens structure, and each parcel has a functional network assignment (e.g. `Visual1`, `Cingulo-Opercular`) . 

The structure name is provided to give an idea of where the parcel is located in the brain, similar to how the cortical parcel names are appended with `-Ctx` to indicate they are cortical parcels.

**Comment by amsinha9** [comment]
Right, that makes sense. We've been using Glasser's 360 parcels + FreeSurfer's 19 subcortical parcels (i.e. cerebellum, thalamus, etc.), so I was under the impression that the network mapping here treated each subcortical structure as a whole. It was a misunderstanding on my part. I appreciate the clarification.
