### ISSUE TITLE
Any volumetric version?

### ISSUE THREAD

**Issue by oliver-xie** [ColeLab/ColeAnticevicNetPartition#25]
Hi! I am using your atlas and want to project the surface atlas back to volumetric space for neurosynth decoding. I know the subcortical ROIs are already in volumetric space but unsure what to do with the cortical parcels. Apologize if this is an easy question.
Thanks,
Oliver

**Comment by sivcek** [comment]
Oliver, hi!

Probably the best way to achieve this is to use `wb_command` to map values to a desired volume space. Based on the list of commands obtained using `wb_command -list-commands`, the best option might be `wb_command -metric-to-volume-mapping`.

All the best, Grega

**Comment by oliver-xie** [comment]
Hi Grega,
Thanks, I figured it out. It was actually covered in a previous [post](https://github.com/ColeLab/ColeAnticevicNetPartition/issues/15) by jielisaji to create a volumetric version of network assignment  
wb_command -label-to-volume-mapping  \ CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_netassignments_R.label.gii \ ../S1200.R.midthickness_MSMAll.32k_fs_LR.surf.gii \ ../S1200_AverageT1w_restore.nii.gz \ CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_netassignments_R.nii.gz \ -nearest-vertex 1

I replaced CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_netassignments_R.label.gii (the one with network index) with one with ROI index. I was just making sure that this isn't something that already exists, which might be helpful to show where the ROIs are for people less familiar with surface maps.

Thanks,
Oliver
