### ISSUE TITLE
about FC Matrix obtained

### ISSUE THREAD

**Issue by wilmerwang** [ColeLab/ColeAnticevicNetPartition#3]
Thanks for making this available, great work!

 **Is there the FC Matrixs with 3D coordinates of MNI space available?**
Maybe just like:
```
x  y  z node_label node_size
-39.5807 -5.71401 51.108	1	1.000000	-
40.2365	-8.38623	52.3802	1	1.000000	-
-19.2128	34.7426	42.474	1	1.000000	-
20.9405	30.7998	43.9931	1	1.000000	-
-17.8767	47.25	-12.8836	1	1.000000	-
17.7395	47.6141	-13.6109	1	1.000000	-
-34.268	32.3246	35.7804	1	1.000000	-
36.5444	32.998	34.1722	1	1.000000	-
-31.9333	50.4556	-9.33333	1	1.000000	-
32.7245	52.3776	-10.5816	1	1.000000	-
-49.3067	13.1779	20.2178	1	1.000000	-
49.3539	14.8219	21.4632	1	1.000000
```
Each row represents a node information. For example, the (x, y, z) is the 3D coordinate of MNI space.

**Comment by wilmerwang** [comment]
@mwcole @jielisaji @ito-takuya

**Comment by wilmerwang** [comment]
The voxels and vertexes coordinates maybe in *.dlabel.nii and *.dscalar.nii files. and I will close this issue.

**Comment by Reine0017** [comment]
Hey @ilikewind! Thanks for posting this, did you manage to get the xyz coordinates of MNI space in the end?

**Comment by wilmerwang** [comment]
> Hey @ilikewind! Thanks for posting this, did you manage to get the xyz coordinates of MNI space in the end?

See https://github.com/ColeLab/ColeAnticevicNetPartition/issues/3#issuecomment-743137101


There are about 60000 vertexes and 30000 voxels as brain coordinates in MRI files and they all called grayordinates. 

1. For vertexes (in surface), you can obtain their surface coordinates in "*.*.midthickness_MSMAll.32k_fs_LR.surf.gii" files. And you can also put the coordinates of the surface into a 3-map metric file, as x, y, z with the command ~~"wb_command -surface-coordinates-to-metric"~~"wb_command -gifti-convert", see https://www.humanconnectome.org/software/workbench-command/-gifti-convert

2. For voxels (not on the surface), you can obtain their coordinates in "CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR.dlabel.nii" file, maybe also in other files.

**Comment by Reine0017** [comment]
Hey @ilikewind! Thanks ALOT for your reply!! I'll try it out!! :)

**Comment by Reine0017** [comment]
Hey @ilikewind! I tried your method 1 and the -surface-coordinates-to-metric function only outputs to .func.gii or .shape.gii files. Sorry if this is a silly question but may I ask how to get the x y z coordinates from there?

**Comment by wilmerwang** [comment]
@Reine0017 Sorry, my bad!

1. List information about the content of a data file by "wb_command -file-information S1200.L.midthickness_MSMAll.32k_fs_LR.surf.gii" and you can see the following table. So we can know there are **32492** surface vertices in **left cortex**.
```bash
Name:                       S1200.L.midthickness_MSMAll.32k_fs_LR.surf.gii
Type:                       Surface
Structure:                  CortexLeft
Data Size:                  1.17 Megabytes
Maps to Surface:            true
Maps to Volume:             false
Maps with LabelTable:       false
Maps with Palette:          false
Number of Vertices:         32492
Number of Triangles:        64980
Normal Vectors Correct:     true
Surface Type (Primary):     Anatomical
Surface Type (Secondary):   Midthickness
X-minimum:                  -64.642
X-maximum:                  0.406
Y-minimum:                  -102.403
Y-maximum:                  67.439
Z-minimum:                  -44.532
Z-maximum:                  75.522
Surface Area:               56619.605
Spacing Mean:               1.485
Spacing Std Dev:            0.428
Spacing Minimum:            0.565
Spacing Maximum:            3.913
```
2.  Decode vertices from "GZipBase64Binary" to "ASCII" by "wb_command -gifti-convert ASCII S1200.L.midthicknes                          s_MSMAll.32k_fs_LR.surf.gii output.surf.gii". 
```bash
# output.surf.gii"
# vertices coordinates in MNI space
   <Data>
      -4.70588 -43.7357 32.7098 
      -18.271 -40.9317 66.6121 
      -51.6597 -6.91174 45.6249 
      -6.65355 21.1627 61.2537 
      -18.9812 -91.0976 19.7982 
      -48.9875 -49.7161 46.5365 
      -37.4477 49.7845 8.22138 
      -1.81655 16.8542 -1.95018 
      -23.2611 -53.7727 -6.19738 
      .......
  </Data>
```
3. "wb_command -file-information CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR.dlabel.nii"
```bash
....
ALONG_COLUMN map type:          BRAIN_MODELS
    Has Volume Data:            true
    Volume Dims:                91,109,91
    Volume Space:               -2,0,0,90;0,2,0,-126;0,0,2,-72
    CortexLeft:                 29696 out of 32492 vertices
    CortexRight:                29716 out of 32492 vertices
    AccumbensLeft:              135 voxels
    AccumbensRight:             140 voxels
    AmygdalaLeft:               315 voxels
    AmygdalaRight:              332 voxels
    BrainStem:                  3472 voxels
    CaudateLeft:                728 voxels
    CaudateRight:               755 voxels
    CerebellumLeft:             8709 voxels
    CerebellumRight:            9144 voxels
    DiencephalonVentralLeft:    706 voxels
    DiencephalonVentralRight:   712 voxels
    HippocampusLeft:            764 voxels
    HippocampusRight:           795 voxels
    PallidumLeft:               297 voxels
    PallidumRight:              260 voxels
    PutamenLeft:                1060 voxels
    PutamenRight:               1010 voxels
    ThalamusLeft:               1288 voxels
    ThalamusRight:              1248 voxels
```
There are 29696 out of 32492 vertices (CortexLeft) in above file and match the vertice (e.g. 1) to MNI coordinate (-18.271, -40.9317, 66.6121 ) in "output.surf.gii". You can also match it by "wb_command -surface-closest-vertex".

4. Convert ijk voxels coordinates to xyz coordinates. 
e.g.
```python
'''
# In CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR.dlabel.nii. 
<TransformationMatrixVoxelIndicesIJKtoXYZ MeterExponent="-3">
-2.0000000 0.0000000 0.0000000 90.0000000 
0.0000000 2.0000000 0.0000000 -126.0000000 
0.0000000 0.0000000 2.0000000 -72.0000000 
0.0000000 0.0000000 0.0000000 1.0000000
</TransformationMatrixVoxelIndicesIJKtoXYZ>
'''
def ijk2xyz(ijk, trans_matrix):
    tmp = np.ones((1, ijk.shape[0]))
    ijk = np.c_[ijk, tmp.T]

    xyz = np.dot(trans_matrix, ijk.T).T
    
    return xyz[:, :3] 

ijk = np.array([[50, 66, 28], [49, 65, 29]])
trans_matrix = np.array([[-2,0,0,90], [0,2,0,-126], [0,0,2,-72], [0,0,0,1]])
xyz = ijk2xyz(ijk, trans_matrix)
# Out[23]:
# array([[-10.,   6., -16.],
#           [ -8.,   4., -14.]])
```

wb_command see https://www.humanconnectome.org/software/workbench-command/

**Comment by Reine0017** [comment]
@ilikewind Thank you SO MUCH for your detailed reply! You're really really too kind :) 

Sorry I hope I don't bother you again after this...But I was trying wondering...do you think it's possible to get the corresponding network associated with each coordinate too? 

Maybe something like: 
x, y, z, networkNumber
-4.70588 -43.7357 32.7098 Network1
-18.271 -40.9317 66.6121 Network3
-51.6597 -6.91174 45.6249 Network5

**Comment by wilmerwang** [comment]
@Reine0017 They are all saved in "CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR.dlabel.nii".

1. Use "wb_command -file-information CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR.dlabel.nii".  There are 718 parcels. 

```bash
......
Label table for ALL maps
         KEY   NAME                                       RED   GREEN    BLUE   ALPHA
           0   ???                                      1.000   1.000   1.000   0.000
           1   Visual1-04_L-Ctx                         0.000   0.000   1.000   1.000
           2   Visual2-28_L-Ctx                         0.392   0.000   1.000   1.000
           3   Visual2-29_L-Ctx                         0.392   0.000   1.000   1.000
           4   Visual2-30_L-Ctx                         0.392   0.000   1.000   1.000
.......
         359   Cingulo-Opercular-28_R-Ctx               0.600   0.000   0.600   1.000
         360   Cingulo-Opercular-29_R-Ctx               0.600   0.000   0.600   1.000
        1010   Visual1-01_L-Accumbens                   0.000   0.000   1.000   1.000
        1020   Visual1-02_L-Accumbens                   0.000   0.000   1.000   1.000
        1030   Visual1-03_R-Accumbens                   0.000   0.000   1.000   1.000
        1040   Visual1-04_R-Accumbens                   0.000   0.000   1.000   1.000
        1050   Visual1-05_L-Brainstem                   0.000   0.000   1.000   1.000
        1060   Visual1-06_L-Brainstem                   0.000   0.000   1.000   1.000
        1070   Visual1-07_R-Brainstem                   0.000   0.000   1.000   1.000
.........
       12140   Orbito-Affective-14_L-Putamen            0.255   0.490   0.000   0.659
       12150   Orbito-Affective-15_L-Putamen            0.255   0.490   0.000   0.659
       12160   Orbito-Affective-16_R-Putamen            0.255   0.490   0.000   0.659
       12170   Orbito-Affective-17_R-Putamen            0.255   0.490   0.000   0.659

```

2. Obtain the labels of grayordinates.
 ```python 
import nibabel as nib
import numpy as np

data = np.array(nib.load("CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR.dlabel.nii").dataobj)

print(data.max(), data.min())
print(data.shape)
## 12170.0 1.0
## (1, 91282)
```
