### ISSUE TITLE
wb_command -cifti-parcellate

### ISSUE THREAD

**Issue by shilpitju** [ColeLab/ColeAnticevicNetPartition#5]
I used the fillowing command:

eval(['!wb_command -cifti-parcellate ' inputFile ' ' parcelCIFTIFile ' COLUMN ' parcelTSFilename ' -method MEAN'])

The output obtained is as:

While running: 
wb_command -cifti-parcellate input.dtseries.nii CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR.dlabel.nii COLUMN Output_Atlas_CortSubcort.Parcels.LR.ptseries.nii -method MEAN 
 
ERROR: input cifti files must have the same volume space 
 
Can someone explain the error to me and the way to run the code. My input dtseries was obtained after processing using fmriprep.

Regards,

Shilpi Modi

**Comment by mwcole** [comment]
It looks like you are using the version of the network partition with both cortical and subcortical regions. Did you include volume-based subcortical voxels in your fmriprep preprocessing? If not that might be why you are getting that error message.

**Comment by shilpitju** [comment]
Thanks so much for your reply. I am getting back to the developers to figure it out.

**Comment by shilpitju** [comment]
In response to the above issue, it was figured out that, HCP volumes are in LAS orientation, while fmriprep produces RAS. I am in continuous communication with the developers to sort out the issue.

Thanks.
