### ISSUE TITLE
Anatomical location of various parcels

### ISSUE THREAD

**Issue by shilpitju** [ColeLab/ColeAnticevicNetPartition#8]
1. In the CortexSubcortex_ColeAnticevic_NetPartition_wSubcorGSR_parcels_LR_LabelKey.txt file, each label/ parcel of a particular network is assigned an index/key value. The hemisphere to which a parcel belongs and whether it’s a cortical/ sub-cortical parcel can be identified. However, is there a way to know exactly to which lobe of the cortex/ anatomical location, a particular parcel  belongs.

2. In the supplimentary table 1 of Glasser, 2016 a table with the description of Glasser cortical parcels is provided. Is the index/ key value same for Cole Parcels as well?

Thanks.

Shilpi Modi

**Comment by mwcole** [comment]
Supplementary table 1 of Glasser (2016) is indeed where you can find anatomical information about the cortical parcels. For the subcortical parcels you would need to identify the MNI coordinates in Connectome Workbench, then look up the anatomical structure somewhere else. Or you could load in the AAL atlas into Workbench and see what anatomical location is listed there. To answer your second question: Yes, the order is the same as in Supplementary Table 1 here: https://static-content.springer.com/esm/art%3A10.1038%2Fnature18933/MediaObjects/41586_2016_BFnature18933_MOESM330_ESM.pdf

**Comment by shilpitju** [comment]
Thank you so much Dr. Cole.

Regards,

Shilpi
