### ISSUE TITLE
Using LoadParcellatedDataInMatlab_Example.m

### ISSUE THREAD

**Issue by shilpitju** [ColeLab/ColeAnticevicNetPartition#9]
Dear Dr. Cole,

I am looking to apply the ColeAnticevic atlas to my data in order to run a parcellated task analysis. I preprocessed my fMRI data using fmriprep and obtain fmri dtseries in fsLR space. 

Can I directly use LoadParcellatedDataInMatlab_Example.m on each subject by using the subject's dtseries as the input file? Is there an additional registration step to be used to make the ColeAnticevic atlas individualized?

**Comment by mwcole** [comment]
Yes, you can use LoadParcellatedDataInMatlab_Example.m to load your dtseries data into MATLAB. Note, however, that you'd want to edit it to exclude the correlation analysis included in the example, since you're planning a task analysis.
